spring:
  application:
    name: demo

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:10MB}

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
    show-sql: false
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}

jwt:
  expiration-at: ${JWT_EXPIRATION_AT:900000}
  expiration-rt: ${JWT_EXPIRATION_RT:604800000}
  secret-key: ${JWT_SECRET}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

app:
  cookie:
    refresh:
      secure: ${REFRESH_COOKIE_SECURE:true}
      same-site: ${REFRESH_COOKIE_SAME_SITE:None}
      domain: ${REFRESH_COOKIE_DOMAIN:}

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

google:
  client-id: ${GOOGLE_CLIENT_ID}
