spring:
  config:
    import: optional:file:../.env[.properties],optional:file:.env[.properties]

  application:
    name: demo

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:10MB}
      
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/test}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:user}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
    show-sql: true

    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  expiration-at: ${JWT_EXPIRATION_AT:900000}
  expiration-rt: ${JWT_EXPIRATION_RT:604800000}
  secret-key: ${JWT_SECRET_KEY:q5X1xZK8F0z+Y3nZ8KpZ9+0rK0z8ZKJ4dZpZq8W1k3M=}

cors:
  allowed-origins: "http://localhost:5173"

app:
  cookie:
    refresh:
      secure: false
      same-site: Lax
      domain: ""
  
cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME:}
  api_key: ${CLOUDINARY_API_KEY:}
  api_secret: ${CLOUDINARY_API_SECRET:}

google:
  client-id: ${GOOGLE_CLIENT_ID:}

vapid:
  public-key: ${VAPID_PUBLIC_KEY:BOLW-aGBFmtFXBlXADxQVoEVLwlkK-qqlDRg6yVY6ABnW360YKzg6vxWcV0jzjxdIXiVHFTaWwDuYfjXwMeiTig}
  private-key: ${VAPID_PRIVATE_KEY:1I34OjRvtqaIW8owD1QaYtcT5v7PjHPyVn7uiMtR0FI}
  subject: ${VAPID_SUBJECT:mailto:admin@rooma.com}
